[package]
name = "zeteb-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
common-utils = { path = "../../../../libs/common-utils" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
