[workspace]
members = [
    "libs/*",
    "services/gcorp.cc/apps/*",
    "services/cardiani/apps/*",
    "services/journa/apps/*",
    "services/zeteb/apps/*",
    "services/godvalley/apps/*",
]
resolver = "2"
