apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sites-ingress
  namespace: gcorp
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: gcorp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gcorp-frontend
                port:
                  number: 3000
    - host: journa.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: journa-frontend
                port:
                  number: 3000
    - host: cardiani.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cardiani-frontend
                port:
                  number: 3000
    - host: zeteb.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zeteb-frontend
                port:
                  number: 3000
