apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cardiani

resources:
  - ../../base/frontend.yaml
  - ../../base/backend.yaml
  - ../../base/redis.yaml
  - ../../base/scylladb.yaml
  - ../../base/configmap.yaml
  - ../../base/secrets.yaml
  - ../../monitoring/redis-exporter.yaml
  - ../../monitoring/scylla-exporter.yaml
  - ingress.yaml

patchesStrategicMerge:
  - frontend-patch.yaml
  - backend-patch.yaml
  - redis-patch.yaml
  - scylladb-patch.yaml